name: Dispatch Event

on: [push]

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Get Branch
        run: echo "::set-env name=BRANCH_NAME::${GITHUB_REF##*/}"
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.PAT_EVENT_DISPATCH }}
          event-type: tlf-custom-event
          client-payload: '{"branch": "${{ env.BRANCH_NAME }}", "sha": "${{ github.sha }}"}'
