name: Consume Event (any)

on:
  repository_dispatch:
    types:
      - tlf-custom-event

jobs:
  consume_any:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'it worked!'
      - run: |
          echo '1: ${{ github.event.client_payload.branch }}'
          echo '2: ${{ github.ref }}'
          echo '3: ${GITHUB_REF##*/}'
