name: Consume Event (any)

on:
  repository_dispatch:
    types:
      - tlf-custom-event

jobs:
  consume_any:
    runs-on: ubuntu-latest
    steps:
      - name: It worked!
        run: echo 'yay!'
