name: Consume Event (any)

on:
  repository_dispatch:
    types:
      - tlf-custom-event

jobs:
  consume_any:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'it worked!'
      - run: |
          echo 'branch: ${{ github.event.client_payload.branch }}'
          echo 'ref: ${{ github.ref }}'
          echo 'sha1: ${{ github.sha }}'
          echo 'sha2: ${{ github.event.client_payload.sha }}'
