name: Consume Event (baz)

on:
  repository_dispatch:
    types:
      - tlf-custom-event

jobs:
  consume_bar:
    if: github.event.client_payload.foo == 'baz'
    runs-on: ubuntu-latest
    steps:
      - name: It worked!
        run: echo 'yay!'
